import { useMemo, useState } from 'react'
import { Badge, EmptyState, Field, inputClass, Modal, primaryButton, secondaryButton, SectionTitle } from '../components/Ui'
import { formatDate } from '../lib/db'

export default function ChallengesPage({db,user,actions,toast}){
  const [filter,setFilter]=useState('Todos')
  const [createOpen,setCreateOpen]=useState(false)
  const [mine,setMine]=useState(false)
  const myTeams=db.teams.filter((t)=>t.miembros.includes(user.id))
  const [form,setForm]=useState({titulo:'',deporte:'Fútbol',ciudad:'Comitán',codigoPostal:user.codigoPostal||'',lugar:'',fecha:'2026-09-28',hora:'17:00',equipoCreadorId:myTeams[0]?.id||''})
  const rows=useMemo(()=>db.challenges.filter((r)=>mine?(r.creadorId===user.id||myTeams.some((t)=>t.id===r.equipoRivalId)):r.estado==='Publicada').filter((r)=>filter==='Todos'||r.deporte===filter),[db.challenges,filter,mine,myTeams,user.id])
  const create=(e)=>{e.preventDefault();if(!form.titulo||!form.lugar||!form.equipoCreadorId)return toast('Completa los datos y selecciona un equipo.','error');actions.createChallenge(form);setCreateOpen(false);toast('Reta publicada correctamente.')}
  const join=(r)=>{if(!myTeams.length)return toast('Necesitas un equipo para aceptar una reta.','error');const result=actions.joinChallenge(r.id,myTeams[0].id);toast(result.message,result.ok?'success':'error')}
  return <>
    <SectionTitle eyebrow="⚔️ Retar" title="RETAR" description="Organiza una nueva reta o busca partidos disponibles cerca de tu zona." actions={<><button className={secondaryButton} onClick={()=>setMine(!mine)}>{mine?'Ver publicadas':'Mis retas'}</button><button className={primaryButton} onClick={()=>setCreateOpen(true)}>📢 Publicar reta</button></>} />
    <div className="mb-6 flex flex-wrap gap-2">{['Todos','Fútbol','Baloncesto','Voleibol'].map((d)=><button key={d} onClick={()=>setFilter(d)} className={`rounded-full px-4 py-2 text-xs font-black ${filter===d?'bg-slate-950 text-white dark:bg-white dark:text-slate-950':'bg-white ring-1 ring-slate-200 dark:bg-slate-900 dark:ring-slate-700'}`}>{d}</button>)}</div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map((r)=><article key={r.id} className="rounded-3xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><h3 className="text-lg font-black">{r.titulo}</h3><Badge tone={r.estado==='Publicada'?'green':'blue'}>{r.estado}</Badge></div><div className="mt-4 space-y-1 text-sm text-slate-600 dark:text-slate-300"><p>⚽ {r.deporte}</p><p>🏟️ {r.lugar}</p><p>📅 {formatDate(r.fecha)} · {r.hora}</p><p>📍 {r.ciudad} · CP {r.codigoPostal}</p></div>{r.estado==='Publicada'&&r.creadorId!==user.id&&<button className={`${primaryButton} mt-5 w-full`} onClick={()=>join(r)}>Aceptar reta</button>}</article>)}</div>
    {!rows.length&&<EmptyState icon="🔥" title={mine?'No tienes retas todavía':'No hay retas publicadas'} description="Puedes publicar una nueva reta para comenzar."/>}
    <Modal open={createOpen} title="Publicar reta" onClose={()=>setCreateOpen(false)}><form className="grid gap-4 sm:grid-cols-2" onSubmit={create}><Field label="Título"><input className={inputClass} value={form.titulo} onChange={(e)=>setForm({...form,titulo:e.target.value})}/></Field><Field label="Deporte"><select className={inputClass} value={form.deporte} onChange={(e)=>setForm({...form,deporte:e.target.value})}><option>Fútbol</option><option>Baloncesto</option><option>Voleibol</option></select></Field><Field label="Mi equipo"><select className={inputClass} value={form.equipoCreadorId} onChange={(e)=>setForm({...form,equipoCreadorId:e.target.value})}><option value="">Seleccionar...</option>{myTeams.map((t)=><option key={t.id} value={t.id}>{t.nombre}</option>)}</select></Field><Field label="Lugar"><input className={inputClass} value={form.lugar} onChange={(e)=>setForm({...form,lugar:e.target.value})}/></Field><Field label="Ciudad"><input className={inputClass} value={form.ciudad} onChange={(e)=>setForm({...form,ciudad:e.target.value})}/></Field><Field label="Código postal"><input className={inputClass} value={form.codigoPostal} onChange={(e)=>setForm({...form,codigoPostal:e.target.value})}/></Field><Field label="Fecha"><input type="date" className={inputClass} value={form.fecha} onChange={(e)=>setForm({...form,fecha:e.target.value})}/></Field><Field label="Hora"><input type="time" className={inputClass} value={form.hora} onChange={(e)=>setForm({...form,hora:e.target.value})}/></Field><button className={`${primaryButton} sm:col-span-2`} type="submit">Publicar reta</button></form></Modal>
  </>
}
