import { useMemo, useState } from 'react'
import { Badge, EmptyState, Field, inputClass, Modal, primaryButton, secondaryButton, SectionTitle, StatCard } from '../components/Ui'
import { formatDate } from '../lib/db'

export default function LeaguesPage({ db, user, actions, toast }) {
  const [search,setSearch]=useState('')
  const [createOpen,setCreateOpen]=useState(false)
  const [admin,setAdmin]=useState(null)
  const [form,setForm]=useState({nombre:'',deporte:'Fútbol',codigoPostal:user.codigoPostal||'',fechaInicio:'2026-10-01',maxEquipos:'8'})
  const myTeams=db.teams.filter((t)=>t.miembros.includes(user.id))
  const filtered=useMemo(()=>db.leagues.filter((l)=>`${l.nombre} ${l.deporte} ${l.codigoPostal}`.toLowerCase().includes(search.toLowerCase())),[db.leagues,search])
  const create=(e)=>{e.preventDefault();if(!form.nombre.trim())return toast('Escribe el nombre de la liga.','error');actions.createLeague(form,myTeams[0]?.id);setCreateOpen(false);toast('Liga creada correctamente.')}
  const join=(league)=>{if(!myTeams.length)return toast('Primero necesitas crear o unirte a un equipo.','error');const result=actions.requestLeague(league.id,myTeams[0].id);toast(result.message,result.ok?'success':'error')}
  return <>
    <SectionTitle eyebrow="🏆 Ligas" title="Panel de ligas" description="Administra tus ligas, revisa en cuáles participas y encuentra opciones para seguir compitiendo." actions={<button className={primaryButton} onClick={()=>setCreateOpen(true)}>＋ Crear una liga</button>} />
    <div className="grid gap-4 sm:grid-cols-3"><StatCard label="Ligas disponibles" value={db.leagues.length} icon="🏆"/><StatCard label="Mis equipos" value={myTeams.length} icon="👥"/><StatCard label="Administradas" value={db.leagues.filter((l)=>l.adminId===user.id).length} icon="⚙️"/></div>
    <div className="my-6"><input className={inputClass} placeholder="Buscar liga, deporte o código postal..." value={search} onChange={(e)=>setSearch(e.target.value)}/></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((l)=>{const adminMine=l.adminId===user.id;const participating=l.equipos.some((id)=>myTeams.some((t)=>t.id===id));return <article key={l.id} className="rounded-3xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black text-blue-600">{l.id}</p><h3 className="mt-1 text-xl font-black">{l.nombre}</h3></div>{adminMine?<Badge tone="green">Administrador</Badge>:participating?<Badge>Participas</Badge>:<Badge tone="slate">Disponible</Badge>}</div><div className="mt-4 space-y-1 text-sm text-slate-600 dark:text-slate-300"><p>⚽ {l.deporte}</p><p>📍 CP {l.codigoPostal}</p><p>📅 Inicio {formatDate(l.fechaInicio)}</p><p>👥 Equipos {l.equipos.length}/{l.maxEquipos}</p></div><div className="mt-5 flex gap-2">{adminMine?<button className={`${primaryButton} flex-1`} onClick={()=>setAdmin(l)}>Administrar</button>:!participating?<button className={`${primaryButton} flex-1`} onClick={()=>join(l)}>Unir mi equipo</button>:<button className={`${secondaryButton} flex-1`} onClick={()=>setAdmin(l)}>Ver liga</button>}</div></article>})}</div>
    {!filtered.length&&<EmptyState title="No hay ligas que coincidan"/>}
    <Modal open={createOpen} title="Crear nueva liga" onClose={()=>setCreateOpen(false)}><form onSubmit={create} className="grid gap-4 sm:grid-cols-2"><Field label="Nombre"><input className={inputClass} value={form.nombre} onChange={(e)=>setForm({...form,nombre:e.target.value})}/></Field><Field label="Deporte"><select className={inputClass} value={form.deporte} onChange={(e)=>setForm({...form,deporte:e.target.value})}><option>Fútbol</option><option>Baloncesto</option><option>Voleibol</option></select></Field><Field label="Código postal"><input className={inputClass} value={form.codigoPostal} onChange={(e)=>setForm({...form,codigoPostal:e.target.value})}/></Field><Field label="Fecha de inicio"><input className={inputClass} type="date" value={form.fechaInicio} onChange={(e)=>setForm({...form,fechaInicio:e.target.value})}/></Field><Field label="Máximo de equipos"><input className={inputClass} type="number" min="2" value={form.maxEquipos} onChange={(e)=>setForm({...form,maxEquipos:e.target.value})}/></Field><button className={`${primaryButton} sm:col-span-2`} type="submit">Crear liga</button></form></Modal>
    <Modal open={!!admin} title={admin?.nombre||'Liga'} onClose={()=>setAdmin(null)} wide>{admin&&<LeagueAdmin league={db.leagues.find((l)=>l.id===admin.id)||admin} db={db} user={user} actions={actions} toast={toast}/>}</Modal>
  </>
}

function LeagueAdmin({league,db,user,actions,toast}){
  const [tab,setTab]=useState('equipos')
  const isAdmin=league.adminId===user.id
  const requests=db.leagueRequests.filter((r)=>r.leagueId===league.id&&r.estado==='Pendiente')
  const teams=league.equipos.map((id)=>db.teams.find((t)=>t.id===id)).filter(Boolean)
  const tabs=['equipos','solicitudes','calendario','tabla','canchas','arbitros']
  return <div><div className="flex flex-wrap gap-2">{tabs.map((t)=><button key={t} className={`rounded-xl px-3 py-2 text-xs font-black capitalize ${tab===t?'bg-slate-950 text-white dark:bg-white dark:text-slate-950':'bg-slate-100 dark:bg-slate-800'}`} onClick={()=>setTab(t)}>{t}</button>)}</div>
  {tab==='equipos'&&<div className="mt-5 space-y-2">{teams.length?teams.map((t)=><div className="rounded-2xl border border-slate-200 p-4 dark:border-slate-700" key={t.id}><p className="font-black">{t.nombre}</p><p className="text-xs text-slate-500">{t.deporte} · {t.miembros.length} integrantes</p></div>):<EmptyState title="Aún no hay equipos"/>}</div>}
  {tab==='solicitudes'&&<div className="mt-5 space-y-3">{requests.length?requests.map((r)=>{const team=db.teams.find((t)=>t.id===r.teamId);return <div key={r.id} className="flex items-center justify-between gap-3 rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><div><p className="font-black">{team?.nombre}</p><p className="text-xs text-slate-500">Solicitud de inscripción</p></div>{isAdmin&&<div className="flex gap-2"><button className={primaryButton} onClick={()=>{actions.resolveLeagueRequest(r.id,true);toast('Equipo aceptado.')}}>Aceptar</button><button className={secondaryButton} onClick={()=>actions.resolveLeagueRequest(r.id,false)}>Rechazar</button></div>}</div>}):<EmptyState title="No hay solicitudes pendientes"/>}</div>}
  {tab==='calendario'&&<div className="mt-5 rounded-3xl bg-slate-50 p-5 text-sm dark:bg-slate-950"><p className="font-black">📅 Calendario</p><p className="mt-2 text-slate-500">La liga inicia el {formatDate(league.fechaInicio)}. Los partidos se pueden registrar desde Agenda.</p></div>}
  {tab==='tabla'&&<div className="mt-5 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-slate-500"><th className="p-3">Equipo</th><th className="p-3">PJ</th><th className="p-3">PTS</th></tr></thead><tbody>{teams.map((t,i)=><tr key={t.id} className="border-t border-slate-200 dark:border-slate-800"><td className="p-3 font-bold">{t.nombre}</td><td className="p-3">{i}</td><td className="p-3">{i*3}</td></tr>)}</tbody></table></div>}
  {tab==='canchas'&&<div className="mt-5 space-y-2">{db.courts.filter((c)=>c.deportes.includes(league.deporte)||c.codigoPostal===league.codigoPostal).slice(0,4).map((c)=><div key={c.id} className="rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><p className="font-black">{c.nombre}</p><p className="text-xs text-slate-500">{c.ciudad} · {c.horario}</p></div>)}</div>}
  {tab==='arbitros'&&<div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-950"><p className="font-black">Árbitro 001</p><Badge tone="green">Disponible</Badge></div><div className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-950"><p className="font-black">Árbitro 002</p><Badge tone="amber">Ocupado</Badge></div></div>}
  </div>
}
